// AUTO-GENERATED icon shim — re-exports Tabler icons under the lucide
// names the codebase uses, translating lucide's `strokeWidth` prop to
// Tabler's `stroke`. Lets us swap the icon set without touching every
// call site. Regenerate via scripts if the icon set changes.
import { forwardRef, createElement } from 'react'
import type { ComponentType } from 'react'
import * as T from '@tabler/icons-react'

export interface IconProps {
  size?: number | string
  strokeWidth?: number | string
  color?: string
  className?: string
  fill?: string
  'aria-hidden'?: boolean | 'true' | 'false'
  [key: string]: unknown
}
export type LucideIcon = ComponentType<IconProps>

function wrap(Comp: unknown): LucideIcon {
  const Wrapped = forwardRef<SVGSVGElement, IconProps>(function Icon(
    { strokeWidth, ...rest }: IconProps,
    ref,
  ) {
    if (!Comp) return null
    return createElement(Comp as ComponentType<Record<string, unknown>>, {
      ref,
      ...(strokeWidth != null ? { stroke: strokeWidth } : {}),
      ...rest,
    })
  })
  return Wrapped as unknown as LucideIcon
}

export const Activity = wrap(T.IconActivity)
export const AlignBoxLeftStretch = wrap(T.IconAlignBoxLeftStretch)
export const AlignBoxRightStretch = wrap(T.IconAlignBoxRightStretch)
export const AlertTriangle = wrap(T.IconAlertTriangle)
export const AppWindow = wrap(T.IconAppWindow)
export const Archive = wrap(T.IconArchive)
export const ArrowDown = wrap(T.IconArrowDown)
export const ArrowLeft = wrap(T.IconArrowLeft)
export const ArrowRight = wrap(T.IconArrowRight)
export const ArrowUp = wrap(T.IconArrowUp)
export const ArrowUpRight = wrap(T.IconArrowUpRight)
export const AudioLines = wrap(T.IconWaveSine)
export const BadgeCheck = wrap(T.IconRosetteDiscountCheck)
export const BadgeDollarSign = wrap(T.IconCurrencyDollar)
export const Ban = wrap(T.IconBan)
export const BarChart3 = wrap(T.IconChartBar)
export const Beaker = wrap(T.IconFlask)
export const Bell = wrap(T.IconBell)
export const Blocks = wrap(T.IconStack2)
export const BookOpen = wrap(T.IconBook)
export const BookText = wrap(T.IconBook2)
export const Bot = wrap(T.IconRobot)
export const Boxes = wrap(T.IconBoxMultiple)
export const BriefcaseBusiness = wrap(T.IconBriefcase)
export const Brush = wrap(T.IconBrush)
export const Calendar = wrap(T.IconCalendar)
export const Camera = wrap(T.IconCamera)
export const Check = wrap(T.IconCheck)
export const CheckCircle2 = wrap(T.IconCircleCheck)
export const CheckSquare = wrap(T.IconSquareCheck)
export const ChevronDown = wrap(T.IconChevronDown)
export const ChevronLeft = wrap(T.IconChevronLeft)
export const ChevronRight = wrap(T.IconChevronRight)
export const ChevronUp = wrap(T.IconChevronUp)
export const CircleAlert = wrap(T.IconAlertCircle)
export const CircleHelp = wrap(T.IconHelpCircle)
export const Clapperboard = wrap(T.IconMovie)
export const Clock = wrap(T.IconClock)
export const Code2 = wrap(T.IconCode)
export const Columns2 = wrap(T.IconColumns)
export const Copy = wrap(T.IconCopy)
export const Cpu = wrap(T.IconCpu)
export const Database = wrap(T.IconDatabase)
export const DollarSign = wrap(T.IconCurrencyDollar)
export const ExternalLink = wrap(T.IconExternalLink)
export const Eye = wrap(T.IconEye)
export const File = wrap(T.IconFile)
export const FileCode2 = wrap(T.IconFileCode)
export const FileCog = wrap(T.IconFileSettings)
export const FileJson = wrap(T.IconFileTypeJs)
export const FileSearch = wrap(T.IconFileSearch)
export const FileText = wrap(T.IconFileText)
export const Film = wrap(T.IconMovie)
export const Flag = wrap(T.IconFlag)
export const Flame = wrap(T.IconFlame)
export const Flashlight = wrap(T.IconBulb)
export const FolderClosed = wrap(T.IconFolder)
export const FolderCode = wrap(T.IconFolderCode)
export const FolderOpen = wrap(T.IconFolderOpen)
export const FolderTree = wrap(T.IconFolders)
export const Gamepad2 = wrap(T.IconDeviceGamepad2)
export const Gauge = wrap(T.IconGauge)
export const Gift = wrap(T.IconGift)
export const GitBranch = wrap(T.IconGitBranch)
export const Globe = wrap(T.IconWorld)
export const Headphones = wrap(T.IconHeadphones)
export const Headset = wrap(T.IconHeadset)
export const Heart = wrap(T.IconHeart)
export const Home = wrap(T.IconHome)
export const History = wrap(T.IconHistory)
export const Image = wrap(T.IconPhoto)
export const ImagePlus = wrap(T.IconPhotoPlus)
export const Inbox = wrap(T.IconInbox)
export const Info = wrap(T.IconInfoCircle)
export const Layers = wrap(T.IconStack2)
export const LayoutDashboard = wrap(T.IconLayoutDashboard)
export const LayoutGrid = wrap(T.IconLayoutGrid)
export const LayoutTemplate = wrap(T.IconLayout)
export const Library = wrap(T.IconBooks)
export const Lightbulb = wrap(T.IconBulb)
export const ListCollapse = wrap(T.IconListTree)
export const ListChecks = wrap(T.IconListCheck)
export const Loader2 = wrap(T.IconLoader2)
export const Mail = wrap(T.IconMail)
export const Menu = wrap(T.IconMenu2)
export const Megaphone = wrap(T.IconSpeakerphone)
export const MessageCircle = wrap(T.IconMessageCircle)
export const MessageCircleHeart = wrap(T.IconMessageHeart)
export const MessageSquare = wrap(T.IconMessage)
export const MessageSquarePlus = wrap(T.IconMessagePlus)
export const MessageSquareText = wrap(T.IconMessage)
export const MessageSquareWarning = wrap(T.IconMessageExclamation)
export const MessagesSquare = wrap(T.IconMessages)
export const Monitor = wrap(T.IconDeviceDesktop)
export const MonitorPlay = wrap(T.IconDeviceTv)
export const Moon = wrap(T.IconMoon)
export const MoreHorizontal = wrap(T.IconDots)
export const Music = wrap(T.IconMusic)
export const Music2 = wrap(T.IconMusic)
export const Palette = wrap(T.IconPalette)
export const PanelLeft = wrap(T.IconLayoutSidebar)
export const PanelRight = wrap(T.IconLayoutSidebarRight)
export const PanelRightOpen = wrap(T.IconLayoutSidebarRightExpand)
export const Paperclip = wrap(T.IconPaperclip)
export const Pencil = wrap(T.IconPencil)
export const PencilLine = wrap(T.IconPencil)
export const Pin = wrap(T.IconPin)
export const PinOff = wrap(T.IconPinnedOff)
export const Star = wrap(T.IconStar)
export const LogOut = wrap(T.IconLogout)
export const Menu4 = wrap(T.IconMenu4)
export const Play = wrap(T.IconPlayerPlay)
export const Crop = wrap(T.IconCrop)
export const Ruler = wrap(T.IconRuler2)
export const Plus = wrap(T.IconPlus)
export const Presentation = wrap(T.IconPresentation)
export const RefreshCw = wrap(T.IconRefresh)
export const Rocket = wrap(T.IconRocket)
export const RotateCcw = wrap(T.IconRotate)
export const Save = wrap(T.IconDeviceFloppy)
export const Scale = wrap(T.IconScale)
export const ScrollText = wrap(T.IconFileDescription)
export const Search = wrap(T.IconSearch)
export const Server = wrap(T.IconServer)
export const Settings = wrap(T.IconSettings)
export const Share2 = wrap(T.IconShare)
export const ShieldAlert = wrap(T.IconShieldExclamation)
export const ShieldCheck = wrap(T.IconShieldCheck)
export const ShoppingBag = wrap(T.IconShoppingBag)
export const ShoppingCart = wrap(T.IconShoppingCart)
export const Smartphone = wrap(T.IconDeviceMobile)
export const Smile = wrap(T.IconMoodSmile)
export const Sparkles = wrap(T.IconSparkles)
export const SquareUser = wrap(T.IconUserSquareRounded)
export const Sun = wrap(T.IconSun)
export const Table = wrap(T.IconTable)
export const Tag = wrap(T.IconTag)
export const Target = wrap(T.IconTarget)
export const Telescope = wrap(T.IconTelescope)
export const Terminal = wrap(T.IconTerminal2)
export const ThumbsDown = wrap(T.IconThumbDown)
export const ThumbsUp = wrap(T.IconThumbUp)
export const Trash2 = wrap(T.IconTrash)
export const TrendingUp = wrap(T.IconTrendingUp)
export const TrendingDown = wrap(T.IconTrendingDown)
export const Type = wrap(T.IconTypography)
export const Upload = wrap(T.IconUpload)
export const User = wrap(T.IconUser)
export const UserRound = wrap(T.IconUserCircle)
export const Users = wrap(T.IconUsers)
export const UsersRound = wrap(T.IconUsersGroup)
export const Video = wrap(T.IconVideo)
export const Volume2 = wrap(T.IconVolume)
export const Wand2 = wrap(T.IconWand)
export const WandSparkles = wrap(T.IconWand)
export const Wrench = wrap(T.IconTool)
export const X = wrap(T.IconX)
export const Zap = wrap(T.IconBolt)
