/* ─── 项目库数据 ───
 *
 * 从 AI 平台 (ai_design) 的 components/app/AppListPage.tsx 原样搬过来，
 * 封面换成本项目 public 下压缩后的 webp。 */

const COVERS = '/assets/workshop/projects'

export type ProjectKind = 'assistant' | 'miniapp' | 'interest' | 'avatar' | 'agent'
export type SpaceKind = 'featured' | 'team' | 'personal'
export type ProjectOrder = 'usage' | 'favorites'

export interface ExperienceProject {
  id: string
  title: string
  description: string
  cover: string
  kind: ProjectKind
  space: SpaceKind
  author?: string
  usage?: string
  favorites?: number
  projectName?: string
  activity?: {
    status: '搭建中' | '交付中' | '已上线'
    phase: string
    period: string
    deliverables: string
    updatedAt: string
    template: string
    tags: readonly string[]
    sources?: readonly {
      label: string
      url: string
      type: 'Figma' | '文档' | '复盘'
    }[]
    investment?: string
    benchmarkOrder?: number
    priority?: string
    evidence?: string
  }
}

export const AUTHOR_AVATAR = `${COVERS}/author.webp`

export const projects: ExperienceProject[] = [
  {
    id: 'team_acg_new_year_2026',
    title: '2026 抖音 ACG 新春会',
    description: '游戏与二次元双会场，覆盖 Lynx 主会场、内容榜单、站内资源位、节目单与结算战报。',
    cover: '/assets/figma-deliverables/acg/discovery-banner-1372x512.png',
    kind: 'assistant',
    space: 'team',
    author: '抖音 ACG 视觉设计',
    favorites: 28,
    projectName: '2026 抖音 ACG 新春会',
    activity: {
      status: '交付中',
      phase: '资源位与战报完善',
      period: '01.09 – 01.16',
      deliverables: '18 项真实交付已归档',
      updatedAt: '今天 15:42',
      template: '新春会模板',
      tags: ['节点大会场', '双会场', 'ACG'],
      benchmarkOrder: 1,
      priority: 'S 级端到端试点',
      evidence: '需求 / 资产 / Figma / 交付全链路可追溯',
      investment: '原流程单项目 21–24 人月',
      sources: [
        { label: '活动复盘', type: '复盘', url: 'https://bytedance.larkoffice.com/wiki/R6w8wU16CihKb7kJlKOcvll8n6c' },
        { label: '设计提案', type: '文档', url: 'https://bytedance.larkoffice.com/wiki/H0wOwf7ToiULAakEOZUckbzSn4g' },
        { label: '创意设计', type: 'Figma', url: 'https://www.figma.com/design/dATx52XsiA0xtpE2xpAeBC/2026-%E6%8A%96%E9%9F%B3ACG%E6%96%B0%E6%98%A5%E4%BC%9A-%E5%88%9B%E6%84%8F?node-id=1690-13237' },
      ],
    },
  },
  {
    id: 'team_spring_gala_2026',
    title: '2026 抖音春晚',
    description: '节目盛典型全渠道活动，真实覆盖话题主入口、Lynx 主会场、H5 抽奖与祝福卡，以及开屏、直播 Tab 和线下屏。',
    cover: '/assets/figma-deliverables/spring-gala/live-main-camera.png',
    kind: 'assistant',
    space: 'team',
    author: '抖音节目活动设计',
    favorites: 35,
    projectName: '2026 抖音春晚',
    activity: {
      status: '交付中',
      phase: '真实案例资产化',
      period: '节目盛典 · 案例归档',
      deliverables: '17 项真实交付已归档',
      updatedAt: '今天 18:36',
      template: '全渠道节目盛典',
      tags: ['直播', '抽奖', '传播矩阵'],
      benchmarkOrder: 3,
      sources: [
        { label: '设计提需', type: '文档', url: 'https://bytedance.larkoffice.com/docx/Si6rdTK8xoK5LUxdrAMc1W1pnRd' },
        { label: '活动页需求', type: '文档', url: 'https://bytedance.larkoffice.com/wiki/TYjgwrRw4iBlVdkh0hCcyI7gnaf' },
        { label: '春晚设计', type: 'Figma', url: 'https://www.figma.com/design/DLhjcvo02Wbwk2PrUAJTkR/2026%E6%98%A5%E6%99%9A-%E5%85%83%E5%AE%B5?node-id=572-114797' },
      ],
    },
  },
  {
    id: 'team_evernight_cards',
    title: '《永夜星河》独星河小卡',
    description: '影视 IP 任务抽卡活动，以任务得次数、单抽/十连、7 卡图鉴与个性化分享卡形成完整参与回路。',
    cover: '/assets/figma-deliverables/evernight/campaign-cover.png',
    kind: 'assistant',
    space: 'team',
    author: '抖音节目活动设计',
    favorites: 52,
    projectName: '《永夜星河》独星河小卡',
    activity: {
      status: '交付中',
      phase: '玩法与卡牌资产归档',
      period: '影视宣发 · 案例归档',
      deliverables: '16 项真实交付已归档',
      updatedAt: '今天 18:12',
      template: '影视 IP · 任务抽卡',
      tags: ['抽卡', '图鉴', '分享回流'],
      benchmarkOrder: 4,
      sources: [
        { label: '活动方案', type: '文档', url: 'https://bytedance.larkoffice.com/docx/VT0edgxzKoyaFXxlaMKcBC8Kn4g' },
        { label: '抽卡设计', type: 'Figma', url: 'https://www.figma.com/design/QyUyHxPLBxH8QvICM9ex5j/%E3%80%8A%E6%B0%B8%E5%A4%9C%E6%98%9F%E6%B2%B3%E3%80%8B%E6%8A%BD%E5%8D%A1?node-id=40-27228' },
      ],
    },
  },
  {
    id: 'team_xiahua_live',
    title: '这夏夯爆了',
    description: '做任务抽美食卡，集齐 2 / 4 / 7 种兑换三档夜食券，已覆盖抖音与极速版入口。',
    cover: '/assets/figma-deliverables/xiahua/food-venue-full.png',
    kind: 'assistant',
    space: 'team',
    author: '生活服务活动中台',
    favorites: 41,
    projectName: '夯爆了 已上线',
    activity: {
      status: '已上线',
      phase: '第二阶段运行中',
      period: '06.30 – 08.31',
      deliverables: '14 项真实交付已归档',
      updatedAt: '昨天 19:08',
      template: '任务抽卡 · 集卡兑奖',
      tags: ['集卡', '券奖励', '多阶段'],
      benchmarkOrder: 2,
      investment: '60 人/日 × 3 个活动阶段',
      sources: [
        { label: 'UGC 活动设计', type: 'Figma', url: 'https://www.figma.com/design/kMedatdeXqtzmq0KOeG0qk/UGC%E6%B4%BB%E5%8A%A8-2026H1?node-id=718-22861' },
      ],
    },
  },
  {
    id: 'team_summer_surf',
    title: '夏日冲浪 · 顺风顺水',
    description: '基于暑期活动模板生成的玩水主题活动，组合任务、装备收集与金豆副玩法。',
    cover: '/assets/marketing-king/theme-assets/summer/hero-scene-v2.png',
    kind: 'assistant',
    space: 'team',
    author: '生活服务创意中台',
    favorites: 12,
    projectName: '夏日冲浪 · 顺风顺水',
    activity: {
      status: '搭建中',
      phase: '玩法与素材联调',
      period: '07.15 – 08.31',
      deliverables: '4 / 6 待确认',
      updatedAt: '今天 11:26',
      template: '暑期收集活动',
      tags: ['玩水', '装备收集', '金豆'],
    },
  },
  {
    id: 'featured_sanguo',
    title: 'SANGUORUSH',
    description: '三国塔防游戏',
    cover: `${COVERS}/sanguorush.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '张文博',
    usage: '48.6k',
  },
  {
    id: 'featured_garuda',
    title: 'Garuda',
    description: '太空射击游戏',
    cover: `${COVERS}/garuda.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '陈若琳',
    usage: '36.2k',
  },
  {
    id: 'featured_azure',
    title: '蔚蓝守卫 Azure Keepers',
    description: '保卫领土的割草游戏',
    cover: `${COVERS}/azure-keepers.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '刘昊然',
    usage: '31.7k',
  },
  {
    id: 'featured_book_of_answers',
    title: '答案之书',
    description: '向 AI 提问，翻开命运之页',
    cover: `${COVERS}/book-of-answers.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '林知夏',
    usage: '28.9k',
  },
  {
    id: 'featured_horoscope',
    title: '天气预报',
    description: '突破传统的天气数据展示',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '周静宜',
    usage: '42.3k',
  },
  {
    id: 'featured_photo_studio',
    title: '冥想时间',
    description: '一键提取高频视频的叙事结构',
    cover: `${COVERS}/photo-studio.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '沈佳宁',
    usage: '26.1k',
  },
  {
    id: 'featured_pop_todo',
    title: '爆款脚本拆解',
    description: '一键提取高赞视频的叙事结构',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '黄美华',
    usage: '22.8k',
  },
  {
    id: 'featured_chinese_colors',
    title: '灵感图文种草机',
    description: '迎合斗音图文带货趋势的创作工具',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '周思远',
    usage: '19.6k',
  },
  {
    id: 'creator_interest_team_travel_guide',
    title: '旅行攻略兴趣卡',
    description: '根据目的地生成可互动的行程与玩法推荐',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '何嘉怡',
    usage: '158k',
    favorites: 36,
  },
  {
    id: 'creator_interest_team_style_match',
    title: '穿搭灵感兴趣卡',
    description: '结合场景和偏好提供个性化穿搭建议',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '苏沐晴',
    usage: '142k',
    favorites: 27,
  },
  {
    id: 'creator_interest_team_hotspot_radar',
    title: '热点趋势兴趣卡',
    description: '聚合热门话题并提供互动式内容灵感',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '陈志强',
    usage: '367k',
    favorites: 14,
  },
  {
    id: 'creator_interest_personal_daily_fortune',
    title: '每日运势兴趣卡',
    description: '查看每日能量、幸运提示与行动建议',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '陆明哲',
    usage: '119k',
    favorites: 21,
  },
  {
    id: 'creator_interest_personal_todo',
    title: '我的待办兴趣卡',
    description: '用轻量互动方式规划并完成每日事项',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '姜若楠',
    usage: '207k',
    favorites: 33,
  },
  {
    id: 'creator_interest_personal_chinese_colors',
    title: '中国色灵感兴趣卡',
    description: '探索传统色彩及其背后的文化故事',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '顾言川',
    usage: '264k',
    favorites: 47,
  },
  {
    id: 'featured_dog_breed_quiz',
    title: '潮玩盲盒抽奖商城',
    description: '一个潮玩盲盒抽奖小程序',
    cover: `${COVERS}/dog-breed-quiz.webp`,
    kind: 'interest',
    space: 'featured',
    author: '林晓彤',
    usage: '17.4k',
  },
  {
    id: 'featured_fashion_styling',
    title: '餐厅在线排队',
    description: '餐饮在线排队叫号小程序',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'interest',
    space: 'featured',
    author: '许文博',
    usage: '15.8k',
  },
  {
    id: 'featured_ielts_vocabulary',
    title: '音频课程',
    description: '一个知识付费小程序',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'interest',
    space: 'featured',
    author: '叶知秋',
    usage: '13.2k',
  },
  {
    id: 'featured_travel_avatar',
    title: '视觉灵感助手',
    description: '一键美化设计草图，提供多风格创意参考',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'avatar',
    space: 'team',
    author: '黄美华',
    usage: '149k',
    favorites: 60,
  },
  {
    id: 'featured_douyin_avatar',
    title: '全网热点雷达',
    description: '实时抓取全网热议话题，为内容创作提供选题',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'agent',
    space: 'team',
    author: '陈志强',
    usage: '367k',
    favorites: 14,
  },
  {
    id: 'personal_copywriting_expert',
    title: '爆文写作专家',
    description: '精通各平台调性，快速生成高转化文案',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'agent',
    space: 'personal',
    author: '吴诗婷',
    usage: '282k',
    favorites: 26,
  },
  {
    id: 'team_video_inspiration',
    title: '视频灵感大师',
    description: '从热点内容中提炼高潜选题与短视频创意',
    cover: `${COVERS}/photo-studio.webp`,
    kind: 'avatar',
    space: 'team',
    author: '沈佳宁',
    usage: '233k',
    favorites: 38,
  },
  {
    id: 'team_brand_avatar',
    title: '品牌视觉分身',
    description: '统一品牌调性，快速生成多场景视觉方案',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'avatar',
    space: 'team',
    author: '周思远',
    usage: '196k',
    favorites: 42,
  },
  {
    id: 'team_product_visual',
    title: '商品创意分身',
    description: '围绕商品卖点生成电商创意与展示素材',
    cover: `${COVERS}/dog-breed-quiz.webp`,
    kind: 'avatar',
    space: 'team',
    author: '林晓彤',
    usage: '174k',
    favorites: 31,
  },
  {
    id: 'team_content_radar',
    title: '内容趋势雷达',
    description: '追踪行业热点，沉淀可执行的内容方向',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'agent',
    space: 'team',
    author: '赵子墨',
    usage: '326k',
    favorites: 55,
  },
  {
    id: 'team_growth_advisor',
    title: '增长策略顾问',
    description: '结合业务数据输出增长诊断与行动建议',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'agent',
    space: 'team',
    author: '许文博',
    usage: '218k',
    favorites: 29,
  },
  {
    id: 'team_customer_insight',
    title: '用户洞察助手',
    description: '分析用户反馈，快速提炼需求与机会点',
    cover: `${COVERS}/azure-keepers.webp`,
    kind: 'agent',
    space: 'team',
    author: '唐雨欣',
    usage: '188k',
    favorites: 24,
  },
  {
    id: 'personal_digital_presenter',
    title: '数字人口播助手',
    description: '根据脚本生成自然流畅的口播表达方案',
    cover: `${COVERS}/book-of-answers.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '陈可欣',
    usage: '126k',
    favorites: 18,
  },
  {
    id: 'personal_travel_avatar',
    title: '旅行灵感分身',
    description: '围绕目的地生成路线、文案和视觉灵感',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '何嘉怡',
    usage: '158k',
    favorites: 36,
  },
  {
    id: 'personal_style_avatar',
    title: '穿搭顾问分身',
    description: '结合场景与偏好提供个性化穿搭建议',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '苏沐晴',
    usage: '142k',
    favorites: 27,
  },
  {
    id: 'personal_knowledge_avatar',
    title: '知识讲解分身',
    description: '将复杂知识整理成清晰易懂的讲解内容',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '陆明哲',
    usage: '119k',
    favorites: 21,
  },
  {
    id: 'personal_content_planner',
    title: '内容规划助手',
    description: '制定内容日历并持续生成高质量选题',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'agent',
    space: 'personal',
    author: '姜若楠',
    usage: '207k',
    favorites: 33,
  },
  {
    id: 'personal_data_assistant',
    title: '数据分析助手',
    description: '快速解读业务数据并生成可视化结论',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'agent',
    space: 'personal',
    author: '顾言川',
    usage: '264k',
    favorites: 47,
  },
  {
    id: 'personal_study_partner',
    title: '学习陪练助手',
    description: '拆解学习目标，提供练习与即时反馈',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'agent',
    space: 'personal',
    author: '叶知秋',
    usage: '175k',
    favorites: 30,
  },
];
