/* ─── 项目库数据 ───
 *
 * 从 AI 平台 (ai_design) 的 components/app/AppListPage.tsx 原样搬过来，
 * 封面换成本项目 public 下压缩后的 webp。 */

const COVERS = '/assets/workshop/projects'

export type ProjectKind = 'assistant' | 'miniapp' | 'interest' | 'avatar' | 'agent'
export type SpaceKind = 'featured' | 'team' | 'personal'
export type ProjectOrder = 'usage' | 'favorites'

export interface ExperienceProject {
  id: string
  title: string
  description: string
  cover: string
  kind: ProjectKind
  space: SpaceKind
  author?: string
  usage?: string
  favorites?: number
}

export const AUTHOR_AVATAR = `${COVERS}/author.webp`

export const projects: ExperienceProject[] = [
  {
    id: 'featured_sanguo',
    title: 'SANGUORUSH',
    description: '三国塔防游戏',
    cover: `${COVERS}/sanguorush.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '张文博',
    usage: '48.6k',
  },
  {
    id: 'featured_garuda',
    title: 'Garuda',
    description: '太空射击游戏',
    cover: `${COVERS}/garuda.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '陈若琳',
    usage: '36.2k',
  },
  {
    id: 'featured_azure',
    title: '蔚蓝守卫 Azure Keepers',
    description: '保卫领土的割草游戏',
    cover: `${COVERS}/azure-keepers.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '刘昊然',
    usage: '31.7k',
  },
  {
    id: 'featured_book_of_answers',
    title: '答案之书',
    description: '向 AI 提问，翻开命运之页',
    cover: `${COVERS}/book-of-answers.webp`,
    kind: 'assistant',
    space: 'featured',
    author: '林知夏',
    usage: '28.9k',
  },
  {
    id: 'featured_horoscope',
    title: '天气预报',
    description: '突破传统的天气数据展示',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '周静宜',
    usage: '42.3k',
  },
  {
    id: 'featured_photo_studio',
    title: '冥想时间',
    description: '一键提取高频视频的叙事结构',
    cover: `${COVERS}/photo-studio.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '沈佳宁',
    usage: '26.1k',
  },
  {
    id: 'featured_pop_todo',
    title: '爆款脚本拆解',
    description: '一键提取高赞视频的叙事结构',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '黄美华',
    usage: '22.8k',
  },
  {
    id: 'featured_chinese_colors',
    title: '灵感图文种草机',
    description: '迎合斗音图文带货趋势的创作工具',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'miniapp',
    space: 'featured',
    author: '周思远',
    usage: '19.6k',
  },
  {
    id: 'creator_interest_team_travel_guide',
    title: '旅行攻略兴趣卡',
    description: '根据目的地生成可互动的行程与玩法推荐',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '何嘉怡',
    usage: '158k',
    favorites: 36,
  },
  {
    id: 'creator_interest_team_style_match',
    title: '穿搭灵感兴趣卡',
    description: '结合场景和偏好提供个性化穿搭建议',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '苏沐晴',
    usage: '142k',
    favorites: 27,
  },
  {
    id: 'creator_interest_team_hotspot_radar',
    title: '热点趋势兴趣卡',
    description: '聚合热门话题并提供互动式内容灵感',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'miniapp',
    space: 'team',
    author: '陈志强',
    usage: '367k',
    favorites: 14,
  },
  {
    id: 'creator_interest_personal_daily_fortune',
    title: '每日运势兴趣卡',
    description: '查看每日能量、幸运提示与行动建议',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '陆明哲',
    usage: '119k',
    favorites: 21,
  },
  {
    id: 'creator_interest_personal_todo',
    title: '我的待办兴趣卡',
    description: '用轻量互动方式规划并完成每日事项',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '姜若楠',
    usage: '207k',
    favorites: 33,
  },
  {
    id: 'creator_interest_personal_chinese_colors',
    title: '中国色灵感兴趣卡',
    description: '探索传统色彩及其背后的文化故事',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'miniapp',
    space: 'personal',
    author: '顾言川',
    usage: '264k',
    favorites: 47,
  },
  {
    id: 'featured_dog_breed_quiz',
    title: '潮玩盲盒抽奖商城',
    description: '一个潮玩盲盒抽奖小程序',
    cover: `${COVERS}/dog-breed-quiz.webp`,
    kind: 'interest',
    space: 'featured',
    author: '林晓彤',
    usage: '17.4k',
  },
  {
    id: 'featured_fashion_styling',
    title: '餐厅在线排队',
    description: '餐饮在线排队叫号小程序',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'interest',
    space: 'featured',
    author: '许文博',
    usage: '15.8k',
  },
  {
    id: 'featured_ielts_vocabulary',
    title: '音频课程',
    description: '一个知识付费小程序',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'interest',
    space: 'featured',
    author: '叶知秋',
    usage: '13.2k',
  },
  {
    id: 'featured_travel_avatar',
    title: '视觉灵感助手',
    description: '一键美化设计草图，提供多风格创意参考',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'avatar',
    space: 'team',
    author: '黄美华',
    usage: '149k',
    favorites: 60,
  },
  {
    id: 'featured_douyin_avatar',
    title: '全网热点雷达',
    description: '实时抓取全网热议话题，为内容创作提供选题',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'agent',
    space: 'team',
    author: '陈志强',
    usage: '367k',
    favorites: 14,
  },
  {
    id: 'personal_copywriting_expert',
    title: '爆文写作专家',
    description: '精通各平台调性，快速生成高转化文案',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'agent',
    space: 'personal',
    author: '吴诗婷',
    usage: '282k',
    favorites: 26,
  },
  {
    id: 'team_video_inspiration',
    title: '视频灵感大师',
    description: '从热点内容中提炼高潜选题与短视频创意',
    cover: `${COVERS}/photo-studio.webp`,
    kind: 'avatar',
    space: 'team',
    author: '沈佳宁',
    usage: '233k',
    favorites: 38,
  },
  {
    id: 'team_brand_avatar',
    title: '品牌视觉分身',
    description: '统一品牌调性，快速生成多场景视觉方案',
    cover: `${COVERS}/chinese-colors.webp`,
    kind: 'avatar',
    space: 'team',
    author: '周思远',
    usage: '196k',
    favorites: 42,
  },
  {
    id: 'team_product_visual',
    title: '商品创意分身',
    description: '围绕商品卖点生成电商创意与展示素材',
    cover: `${COVERS}/dog-breed-quiz.webp`,
    kind: 'avatar',
    space: 'team',
    author: '林晓彤',
    usage: '174k',
    favorites: 31,
  },
  {
    id: 'team_content_radar',
    title: '内容趋势雷达',
    description: '追踪行业热点，沉淀可执行的内容方向',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'agent',
    space: 'team',
    author: '赵子墨',
    usage: '326k',
    favorites: 55,
  },
  {
    id: 'team_growth_advisor',
    title: '增长策略顾问',
    description: '结合业务数据输出增长诊断与行动建议',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'agent',
    space: 'team',
    author: '许文博',
    usage: '218k',
    favorites: 29,
  },
  {
    id: 'team_customer_insight',
    title: '用户洞察助手',
    description: '分析用户反馈，快速提炼需求与机会点',
    cover: `${COVERS}/azure-keepers.webp`,
    kind: 'agent',
    space: 'team',
    author: '唐雨欣',
    usage: '188k',
    favorites: 24,
  },
  {
    id: 'personal_digital_presenter',
    title: '数字人口播助手',
    description: '根据脚本生成自然流畅的口播表达方案',
    cover: `${COVERS}/book-of-answers.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '陈可欣',
    usage: '126k',
    favorites: 18,
  },
  {
    id: 'personal_travel_avatar',
    title: '旅行灵感分身',
    description: '围绕目的地生成路线、文案和视觉灵感',
    cover: `${COVERS}/travel-avatar.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '何嘉怡',
    usage: '158k',
    favorites: 36,
  },
  {
    id: 'personal_style_avatar',
    title: '穿搭顾问分身',
    description: '结合场景与偏好提供个性化穿搭建议',
    cover: `${COVERS}/fashion-styling.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '苏沐晴',
    usage: '142k',
    favorites: 27,
  },
  {
    id: 'personal_knowledge_avatar',
    title: '知识讲解分身',
    description: '将复杂知识整理成清晰易懂的讲解内容',
    cover: `${COVERS}/horoscope.webp`,
    kind: 'avatar',
    space: 'personal',
    author: '陆明哲',
    usage: '119k',
    favorites: 21,
  },
  {
    id: 'personal_content_planner',
    title: '内容规划助手',
    description: '制定内容日历并持续生成高质量选题',
    cover: `${COVERS}/pop-todo.webp`,
    kind: 'agent',
    space: 'personal',
    author: '姜若楠',
    usage: '207k',
    favorites: 33,
  },
  {
    id: 'personal_data_assistant',
    title: '数据分析助手',
    description: '快速解读业务数据并生成可视化结论',
    cover: `${COVERS}/douyin-avatar.webp`,
    kind: 'agent',
    space: 'personal',
    author: '顾言川',
    usage: '264k',
    favorites: 47,
  },
  {
    id: 'personal_study_partner',
    title: '学习陪练助手',
    description: '拆解学习目标，提供练习与即时反馈',
    cover: `${COVERS}/ielts-vocabulary.webp`,
    kind: 'agent',
    space: 'personal',
    author: '叶知秋',
    usage: '175k',
    favorites: 30,
  },
];

